steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - freefall_solver
  - --region=europe-west1
  - --source=./freefall-solver/
  - --trigger-http
  - --runtime=python39